### ISSUE TITLE
Rolling list of files that the OCR step fails on

### ISSUE THREAD

**Issue by evz** [datamade/elpc_bakken#4]
W21826.pdf
W22535.pdf
W27321.pdf
W27532.pdf
W28541.pdf
W28554.pdf
W28555.pdf
W28556.pdf
W28557.pdf
W28608.pdf
W28744.pdf
W28765.pdf
W28812.pdf
W28813.pdf
W28834.pdf
W28971.pdf
W29038.pdf

The error that is thrown always looks like this (so far):

```
ocrfeeder-cli -e TESSERACT -f HTML -i \
  `echo W28556_images/*.ppm | sed 's/ / -i /g'` -o W28556_text
Traceback (most recent call last):
  File "/usr/bin/ocrfeeder-cli", line 137, in <module>
    resolution)
  File "/usr/lib/python2.7/dist-packages/ocrfeeder/feeder/layoutAnalysis.py", line 472, in recognize
    blocks = block_retriever.getAllBlocks()
  File "/usr/lib/python2.7/dist-packages/ocrfeeder/feeder/layoutAnalysis.py", line 373, in getAllBlocks
    blocks = self.extendBlocksByBelongingSingles()
  File "/usr/lib/python2.7/dist-packages/ocrfeeder/feeder/layoutAnalysis.py", line 308, in extendBlocksByBelongingSingles
    block = blocks[i]
IndexError: list index out of range
Makefile:11: recipe for target 'W28556_text' failed
make: *** [W28556_text] Error 1
```

**Comment by evz** [comment]
A new error type just cropped up for W28887:

```
Traceback (most recent call last):
  File "/usr/bin/ocrfeeder-cli", line 137, in <module>
    resolution)
  File "/usr/lib/python2.7/dist-packages/ocrfeeder/feeder/layoutAnalysis.py", line 495, in recognize
    for bounds in block_bounds]
  File "/usr/lib/python2.7/dist-packages/ocrfeeder/feeder/layoutAnalysis.py", line 504, in __recognizeImageFromBounds
    text = self.readImage(clip)
  File "/usr/lib/python2.7/dist-packages/ocrfeeder/feeder/layoutAnalysis.py", line 546, in readImage
    self.ocr_engine.setImage(image)
  File "/usr/lib/python2.7/dist-packages/ocrfeeder/feeder/ocrEngines.py", line 68, in setImage
    image.save(image_file)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1685, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python2.7/dist-packages/PIL/TiffImagePlugin.py", line 1201, in _save
    ("raw", (0, 0)+im.size, offset, (rawmode, stride, 1))
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFile.py", line 491, in _save
    e.setimage(im.im, b)
SystemError: tile cannot extend outside image
Makefile:11: recipe for target 'W28887_text' failed
```
